# Generated by Django 5.1.4 on 2025-01-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdapp', '0003_profile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='idea_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='idea_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
