# Generated by Django 5.1.4 on 2025-01-23 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdapp', '0005_remove_profile_idea_desc_remove_profile_idea_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='category',
            field=models.CharField(choices=[('Computer science', 'Computer science'), ('Technology', 'Technology'), ('Science', 'Science'), ('Business', 'Business'), ('Art', 'Art')], default='Computer science', max_length=50),
        ),
        migrations.AlterField(
            model_name='idea',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
