# Generated by Django 5.1.4 on 2025-01-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdapp', '0006_idea_category_alter_idea_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='category',
            field=models.CharField(choices=[('Computer science', 'Computer science'), ('Technology', 'Technology'), ('Science', 'Science'), ('Business', 'Business'), ('Art', 'Art')], default='', max_length=50),
        ),
    ]
