# Generated by Django 5.1.4 on 2025-01-23 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdapp', '0009_remove_idea_created_at_ideavote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ideavote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ideavote',
            name='vote_type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default='like', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ideavote',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdapp.idea'),
        ),
        migrations.RemoveField(
            model_name='ideavote',
            name='is_like',
        ),
    ]
